FROM strapi/base

# Create and change to the app directory.
WORKDIR /usr/src/app
ENV NODE_ENV=production

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy local code to the container image.
COPY . ./

# Build Strapi
RUN npm run build

# Define the port container works on
EXPOSE 1337

# Run the web service on container startup.
CMD [ "npm", "start" ]
